#!/bin/bash
INPUT=$1 #~/Desktop/languages_pt.csv
OUTPUT=${INPUT%.*}.xml
OLDIFS=$IFS
IFS=,
[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 99; }
echo "<?xml version="\"1.0"\" encoding="\"utf-8?"\">" > $OUTPUT
echo "<resources>" >> $OUTPUT
while read string_name string_value
do
	echo "<string name="\"$string_name"\">$string_value</string>" >> $OUTPUT
done < $INPUT
IFS=$OLDIFS
echo "</resources>" >> $OUTPUT
#sed 's/\n//' $OUTPUT
